//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heegar.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeType
    {
        public CodeType()
        {
            this.CodeSamples = new HashSet<CodeSample>();
        }
    
        public int CodeTypeID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CodeSample> CodeSamples { get; set; }
    }
}
