//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heegar.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeSample
    {
        public int CodeSampleID { get; set; }
        public int CodeTypeID { get; set; }
        public string ShortDescription { get; set; }
        public string DetailedNotes { get; set; }
    
        public virtual CodeType CodeType { get; set; }
    }
}
